name: Code Inspector

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-format:
    name: Check Code format

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Display Python version
        run: python -V
      - name: Install isort, black and pylint
        run: python -m pip install --upgrade pip isort black pylint
      - name: Install requirements
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run isort
        run: isort --check --diff *
      - name: Run black
        run: black --check --diff --color .
      - name: Run Pylint on project directory
        run: pylint project_dir
      - name: Run Pylint on test directory
        run: pylint tests/*.py
  run-pytest:
    name: Run Pytest

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Display Python version
        run: python -V
      - name: Install pytest
        run: python -m pip install --upgrade pip pytest
      - name: Install requirements
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Pytest
        run: pytest -v tests
