name: Run Linters

on: [push, pull_request]

jobs:
  run-pylint:
    name: Run Pylint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Display Python version
        run: python -V
      - name: Install pylint
        run: python -m pip install --upgrade pip pylint
      - name: Install requirements
        run: if [ -f requirements.txt ]; then pip install -r requirements.txt; elif [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Run Pylint
        run: pylint project_dir
